In [ ]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf
import os
from tensorflow.keras.callbacks import ModelCheckpoint

#  Import and read the charity_data.csv.
import pandas as pd
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [ ]:
# Drop the non-beneficial ID columns, 'EIN' , 'NAME', 'STATUS' and 'SPECIAL_CONSIDERATIONS'.
application_df = application_df.drop(columns = ['EIN'])
application_df.head()

,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [14]:
#Look at NAME value counts for binning
name_counts = application_df['NAME'].value_counts()
name_counts

PARENT BOOSTER USA INC                                                  1260
TOPS CLUB INC                                                            765
UNITED STATES BOWLING CONGRESS INC                                       700
WASHINGTON STATE UNIVERSITY                                              492
AMATEUR ATHLETIC UNION OF THE UNITED STATES INC                          408
                                                                        ...
ST LOUIS SLAM WOMENS FOOTBALL                                              1
AIESEC ALUMNI IBEROAMERICA CORP                                            1
WEALLBLEEDRED ORG INC                                                      1
AMERICAN SOCIETY FOR STANDARDS IN MEDIUMSHIP & PSYCHICAL INVESTIGATI       1
WATERHOUSE CHARITABLE TR                                                   1
Name: NAME, Length: 19568, dtype: int64

In [15]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
name_types_to_replace = list(name_counts[name_counts < 5].index)

# Replace in dataframe
for app in name_types_to_replace:
    application_df['NAME'] = application_df['NAME'].replace(app,"Other")

# Check to make sure binning was successful
application_df['NAME'].value_counts()

Other                                                                19803
PARENT BOOSTER USA INC                                                1260
TOPS CLUB INC                                                          765
UNITED STATES BOWLING CONGRESS INC                                     700
WASHINGTON STATE UNIVERSITY                                            492
                                                                     ...
GUILDS OF THE SANTA FE OPERA INC                                         5
FAMILY MOTOR COACH ASSOCIATION                                           5
JAMESTOWN SOCIETY                                                        5
MOST WORSHIPFUL PRINCE HALL GRAND LODGE OF FREE & ACCEPTED MASONS        5
PTA HAWAII CONGRESS                                                      5
Name: NAME, Length: 403, dtype: int64

In [16]:
# Determine the number of unique values in each column.
application_df.nunique()

NAME                       403
APPLICATION_TYPE             9
AFFILIATION                  6
CLASSIFICATION               7
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [17]:
# Look at APPLICATION_TYPE value counts for binning
application_counts = application_df['APPLICATION_TYPE'].value_counts()
application_counts

T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: APPLICATION_TYPE, dtype: int64

In [18]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
application_types_to_replace = list(application_counts[application_counts < 500].index)

# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure binning was successful
application_df['APPLICATION_TYPE'].value_counts()

T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: APPLICATION_TYPE, dtype: int64

In [21]:
# Look at CLASSIFICATION value counts for binning
classification_counts = application_df['CLASSIFICATION'].value_counts()
classification_counts

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
Other     1484
C7000      777
Name: CLASSIFICATION, dtype: int64

In [22]:
# You may find it helpful to look at CLASSIFICATION value counts >1
classification_counts[classification_counts > 1]

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
Other     1484
C7000      777
Name: CLASSIFICATION, dtype: int64

In [23]:
# Choose a cutoff value and create a list of classification to be replaced
# use the variable name `classifications_to_replace`
classification_to_replace = list(classification_counts[classification_counts < 500].index)

# Replace in dataframe
for cls in classification_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")

# Check to make sure binning was successful
application_df['CLASSIFICATION'].value_counts()
application_df

,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,Other,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,Other,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,Other,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,Other,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1
...,...,...,...,...,...,...,...,...,...,...,...
34294,Other,T4,Independent,C1000,ProductDev,Association,1,0,N,5000,0
34295,INTERNATIONAL ASSOCIATION OF LIONS CLUBS,T4,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
34296,PTA HAWAII CONGRESS,T3,CompanySponsored,C2000,Preservation,Association,1,0,N,5000,0
34297,Other,T5,Independent,C3000,ProductDev,Association,1,0,N,5000,1
34298,Other,T3,Independent,C1000,Preservation,Co-operative,1,1M-5M,N,36500179,0

In [24]:
# Convert categorical data to numeric with `pd.get_dummies`
application_clean_df = pd.get_dummies(application_df)
application_clean_df

,STATUS,ASK_AMT,IS_SUCCESSFUL,NAME_AACE INTERNATIONAL,NAME_ACE MENTOR PROGRAM OF AMERICA INC,NAME_ACTS MINISTRY,NAME_ACTS MISSIONS,NAME_AFRICAN-AMERICAN POSTAL LEAGUE UNITED FOR SUCCESS A-PLUS,NAME_AIR FORCE ASSOCIATION,NAME_ALABAMA FEDERATION OF WOMENS CLUBS,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1,1,108590,1,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,1,0
2,1,5000,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
3,1,6692,1,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,1,0
4,1,142590,1,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34294,1,5000,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
34295,1,5000,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
34296,1,5000,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
34297,1,5000,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
34298,1,36500179,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,1,0

In [25]:
# Split our preprocessed data into our features and target arrays
X = application_clean_df.drop(columns = 'IS_SUCCESSFUL').values
y = application_clean_df.IS_SUCCESSFUL.values

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2,random_state = 42)

In [26]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [31]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.

number_input_features = X_train.shape[1]

nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(tf.keras.layers.Dense(units = 10, activation = 'relu', input_dim = number_input_features ))

# Second hidden layer
nn.add(tf.keras.layers.Dense(units = 20, activation = 'relu'))

# Output layer
nn.add(tf.keras.layers.Dense(units = 1, activation = 'sigmoid'))



# Check the structure of the model
nn.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_3 (Dense)             (None, 10)                4480

 dense_4 (Dense)             (None, 20)                220

 dense_5 (Dense)             (None, 1)                 21

=================================================================
Total params: 4721 (18.44 KB)
Trainable params: 4721 (18.44 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [32]:
# Compile the model
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [33]:
# Define the checkpoint path and file names
os.makedirs("checkpoints-Optimization/", exist_ok=True)
path = "checkpoints-Optimization/weights.{epoch:02d}.hdf5"

In [34]:
# Create a callback that saves the model's weights every five epochs
checkpoint_callback = ModelCheckpoint(filepath=path, verbose=2, save_weights_only=True, save_freq='epoch', period=5)

# Train the model
nn.fit(X_train_scaled, y_train, epochs=100, callbacks=[checkpoint_callback])

WARNING:tensorflow:`period` argument is deprecated. Please use `save_freq` to specify the frequency in number of batches seen.

Epoch 1/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5102 - accuracy: 0.7588
Epoch 2/100
858/858 [==============================] - 1s 1ms/step - loss: 0.4378 - accuracy: 0.7948
Epoch 3/100
858/858 [==============================] - 1s 1ms/step - loss: 0.4292 - accuracy: 0.7973
Epoch 4/100
858/858 [==============================] - 1s 1ms/step - loss: 0.4258 - accuracy: 0.7964
Epoch 5/100
819/858 [===========================>..] - ETA: 0s - loss: 0.4245 - accuracy: 0.7977
Epoch 5: saving model to checkpoints-Optimization/weights.05.hdf5
858/858 [==============================] - 1s 1ms/step - loss: 0.4244 - accuracy: 0.7976
Epoch 6/100
858/858 [==============================] - 1s 1ms/step - loss: 0.4228 - accuracy: 0.7973
Epoch 7/100
858/858 [==============================] - 1s 1ms/step - loss: 0.4220 - accuracy: 0.7972
Epoch 8/100
858/858 [==============================] - 1s 1ms/step - loss: 0.4210 - accuracy: 0.7991
Epoch 9/100
858/858 [==============================] - 1s 1ms/step - loss: 0.4202 - accuracy: 0.7980
Epoch 10/100
845/858 [============================>.] - ETA: 0s - loss: 0.4193 - accuracy: 0.7980
Epoch 10: saving model to checkpoints-Optimization/weights.10.hdf5
858/858 [==============================] - 1s 1ms/step - loss: 0.4193 - accuracy: 0.7981
Epoch 11/100
858/858 [==============================] - 2s 2ms/step - loss: 0.4187 - accuracy: 0.8007
Epoch 12/100
858/858 [==============================] - 1s 1ms/step - loss: 0.4184 - accuracy: 0.7998
Epoch 13/100
858/858 [==============================] - 1s 1ms/step - loss: 0.4175 - accuracy: 0.7991
Epoch 14/100
858/858 [==============================] - 1s 1ms/step - loss: 0.4177 - accuracy: 0.8005
Epoch 15/100
843/858 [============================>.] - ETA: 0s - loss: 0.4170 - accuracy: 0.8002
Epoch 15: saving model to checkpoints-Optimization/weights.15.hdf5
858/858 [==============================] - 1s 1ms/step - loss: 0.4169 - accuracy: 0.8002
Epoch 16/100
858/858 [==============================] - 1s 1ms/step - loss: 0.4161 - accuracy: 0.8019
Epoch 17/100
858/858 [==============================] - 1s 1ms/step - loss: 0.4160 - accuracy: 0.8013
Epoch 18/100
858/858 [==============================] - 1s 1ms/step - loss: 0.4158 - accuracy: 0.8013
Epoch 19/100
858/858 [==============================] - 1s 1ms/step - loss: 0.4156 - accuracy: 0.8026
Epoch 20/100
854/858 [============================>.] - ETA: 0s - loss: 0.4150 - accuracy: 0.8028
Epoch 20: saving model to checkpoints-Optimization/weights.20.hdf5
858/858 [==============================] - 1s 1ms/step - loss: 0.4150 - accuracy: 0.8028
Epoch 21/100
858/858 [==============================] - 1s 2ms/step - loss: 0.4151 - accuracy: 0.8032
Epoch 22/100
858/858 [==============================] - 1s 1ms/step - loss: 0.4145 - accuracy: 0.8035
Epoch 23/100
858/858 [==============================] - 1s 1ms/step - loss: 0.4140 - accuracy: 0.8031
Epoch 24/100
858/858 [==============================] - 1s 1ms/step - loss: 0.4144 - accuracy: 0.8032
Epoch 25/100
844/858 [============================>.] - ETA: 0s - loss: 0.4139 - accuracy: 0.8024
Epoch 25: saving model to checkpoints-Optimization/weights.25.hdf5
858/858 [==============================] - 1s 1ms/step - loss: 0.4139 - accuracy: 0.8028
Epoch 26/100
858/858 [==============================] - 1s 1ms/step - loss: 0.4131 - accuracy: 0.8029
Epoch 27/100
858/858 [==============================] - 1s 1ms/step - loss: 0.4127 - accuracy: 0.8033
Epoch 28/100
858/858 [==============================] - 1s 1ms/step - loss: 0.4117 - accuracy: 0.8041
Epoch 29/100
858/858 [==============================] - 1s 1ms/step - loss: 0.4113 - accuracy: 0.8048
Epoch 30/100
848/858 [============================>.] - ETA: 0s - loss: 0.4113 - accuracy: 0.8050
Epoch 30: saving model to checkpoints-Optimization/weights.30.hdf5
858/858 [==============================] - 1s 1ms/step - loss: 0.4111 - accuracy: 0.8050
Epoch 31/100
858/858 [==============================] - 1s 2ms/step - loss: 0.4105 - accuracy: 0.8041
Epoch 32/100
858/858 [==============================] - 1s 1ms/step - loss: 0.4105 - accuracy: 0.8033
Epoch 33/100
858/858 [==============================] - 1s 1ms/step - loss: 0.4104 - accuracy: 0.8041
Epoch 34/100
858/858 [==============================] - 1s 1ms/step - loss: 0.4103 - accuracy: 0.8043
Epoch 35/100
858/858 [==============================] - ETA: 0s - loss: 0.4098 - accuracy: 0.8041
Epoch 35: saving model to checkpoints-Optimization/weights.35.hdf5
858/858 [==============================] - 1s 1ms/step - loss: 0.4098 - accuracy: 0.8041
Epoch 36/100
858/858 [==============================] - 1s 1ms/step - loss: 0.4098 - accuracy: 0.8047
Epoch 37/100
858/858 [==============================] - 1s 1ms/step - loss: 0.4098 - accuracy: 0.8043
Epoch 38/100
858/858 [==============================] - 1s 1ms/step - loss: 0.4094 - accuracy: 0.8054
Epoch 39/100
858/858 [==============================] - 1s 1ms/step - loss: 0.4093 - accuracy: 0.8046
Epoch 40/100
847/858 [============================>.] - ETA: 0s - loss: 0.4093 - accuracy: 0.8055
Epoch 40: saving model to checkpoints-Optimization/weights.40.hdf5
858/858 [==============================] - 1s 1ms/step - loss: 0.4093 - accuracy: 0.8054
Epoch 41/100
858/858 [==============================] - 1s 2ms/step - loss: 0.4091 - accuracy: 0.8045
Epoch 42/100
858/858 [==============================] - 1s 1ms/step - loss: 0.4090 - accuracy: 0.8054
Epoch 43/100
858/858 [==============================] - 1s 1ms/step - loss: 0.4088 - accuracy: 0.8060
Epoch 44/100
858/858 [==============================] - 1s 1ms/step - loss: 0.4085 - accuracy: 0.8060
Epoch 45/100
823/858 [===========================>..] - ETA: 0s - loss: 0.4093 - accuracy: 0.8049
Epoch 45: saving model to checkpoints-Optimization/weights.45.hdf5
858/858 [==============================] - 1s 1ms/step - loss: 0.4085 - accuracy: 0.8053
Epoch 46/100
858/858 [==============================] - 1s 1ms/step - loss: 0.4080 - accuracy: 0.8058
Epoch 47/100
858/858 [==============================] - 1s 1ms/step - loss: 0.4080 - accuracy: 0.8052
Epoch 48/100
858/858 [==============================] - 1s 1ms/step - loss: 0.4080 - accuracy: 0.8051
Epoch 49/100
858/858 [==============================] - 1s 1ms/step - loss: 0.4083 - accuracy: 0.8049
Epoch 50/100
833/858 [============================>.] - ETA: 0s - loss: 0.4076 - accuracy: 0.8050
Epoch 50: saving model to checkpoints-Optimization/weights.50.hdf5
858/858 [==============================] - 1s 1ms/step - loss: 0.4076 - accuracy: 0.8055
Epoch 51/100
858/858 [==============================] - 1s 2ms/step - loss: 0.4074 - accuracy: 0.8057
Epoch 52/100
858/858 [==============================] - 1s 1ms/step - loss: 0.4073 - accuracy: 0.8055
Epoch 53/100
858/858 [==============================] - 1s 1ms/step - loss: 0.4074 - accuracy: 0.8057
Epoch 54/100
858/858 [==============================] - 1s 1ms/step - loss: 0.4072 - accuracy: 0.8059
Epoch 55/100
822/858 [===========================>..] - ETA: 0s - loss: 0.4069 - accuracy: 0.8069
Epoch 55: saving model to checkpoints-Optimization/weights.55.hdf5
858/858 [==============================] - 1s 1ms/step - loss: 0.4072 - accuracy: 0.8064
Epoch 56/100
858/858 [==============================] - 1s 1ms/step - loss: 0.4067 - accuracy: 0.8048
Epoch 57/100
858/858 [==============================] - 1s 1ms/step - loss: 0.4067 - accuracy: 0.8064
Epoch 58/100
858/858 [==============================] - 1s 1ms/step - loss: 0.4068 - accuracy: 0.8061
Epoch 59/100
858/858 [==============================] - 1s 1ms/step - loss: 0.4068 - accuracy: 0.8056
Epoch 60/100
835/858 [============================>.] - ETA: 0s - loss: 0.4070 - accuracy: 0.8054
Epoch 60: saving model to checkpoints-Optimization/weights.60.hdf5
858/858 [==============================] - 1s 2ms/step - loss: 0.4066 - accuracy: 0.8058
Epoch 61/100
858/858 [==============================] - 1s 2ms/step - loss: 0.4068 - accuracy: 0.8053
Epoch 62/100
858/858 [==============================] - 1s 1ms/step - loss: 0.4063 - accuracy: 0.8060
Epoch 63/100
858/858 [==============================] - 1s 1ms/step - loss: 0.4064 - accuracy: 0.8059
Epoch 64/100
858/858 [==============================] - 1s 1ms/step - loss: 0.4064 - accuracy: 0.8058
Epoch 65/100
832/858 [============================>.] - ETA: 0s - loss: 0.4060 - accuracy: 0.8065
Epoch 65: saving model to checkpoints-Optimization/weights.65.hdf5
858/858 [==============================] - 1s 1ms/step - loss: 0.4063 - accuracy: 0.8063
Epoch 66/100
858/858 [==============================] - 1s 1ms/step - loss: 0.4060 - accuracy: 0.8059
Epoch 67/100
858/858 [==============================] - 1s 1ms/step - loss: 0.4059 - accuracy: 0.8064
Epoch 68/100
858/858 [==============================] - 1s 1ms/step - loss: 0.4058 - accuracy: 0.8071
Epoch 69/100
858/858 [==============================] - 1s 1ms/step - loss: 0.4058 - accuracy: 0.8061
Epoch 70/100
858/858 [==============================] - ETA: 0s - loss: 0.4060 - accuracy: 0.8067
Epoch 70: saving model to checkpoints-Optimization/weights.70.hdf5
858/858 [==============================] - 1s 1ms/step - loss: 0.4060 - accuracy: 0.8067
Epoch 71/100
858/858 [==============================] - 1s 2ms/step - loss: 0.4058 - accuracy: 0.8066
Epoch 72/100
858/858 [==============================] - 1s 1ms/step - loss: 0.4061 - accuracy: 0.8063
Epoch 73/100
858/858 [==============================] - 2s 2ms/step - loss: 0.4053 - accuracy: 0.8061
Epoch 74/100
858/858 [==============================] - 1s 1ms/step - loss: 0.4056 - accuracy: 0.8069
Epoch 75/100
823/858 [===========================>..] - ETA: 0s - loss: 0.4058 - accuracy: 0.8073
Epoch 75: saving model to checkpoints-Optimization/weights.75.hdf5
858/858 [==============================] - 1s 1ms/step - loss: 0.4057 - accuracy: 0.8072
Epoch 76/100
858/858 [==============================] - 1s 1ms/step - loss: 0.4053 - accuracy: 0.8071
Epoch 77/100
858/858 [==============================] - 1s 1ms/step - loss: 0.4054 - accuracy: 0.8070
Epoch 78/100
858/858 [==============================] - 1s 1ms/step - loss: 0.4053 - accuracy: 0.8067
Epoch 79/100
858/858 [==============================] - 1s 1ms/step - loss: 0.4055 - accuracy: 0.8064
Epoch 80/100
858/858 [==============================] - ETA: 0s - loss: 0.4048 - accuracy: 0.8064
Epoch 80: saving model to checkpoints-Optimization/weights.80.hdf5
858/858 [==============================] - 1s 2ms/step - loss: 0.4048 - accuracy: 0.8064
Epoch 81/100
858/858 [==============================] - 1s 1ms/step - loss: 0.4050 - accuracy: 0.8063
Epoch 82/100
858/858 [==============================] - 1s 1ms/step - loss: 0.4051 - accuracy: 0.8067
Epoch 83/100
858/858 [==============================] - 1s 1ms/step - loss: 0.4047 - accuracy: 0.8081
Epoch 84/100
858/858 [==============================] - 1s 1ms/step - loss: 0.4048 - accuracy: 0.8068
Epoch 85/100
824/858 [===========================>..] - ETA: 0s - loss: 0.4046 - accuracy: 0.8074
Epoch 85: saving model to checkpoints-Optimization/weights.85.hdf5
858/858 [==============================] - 1s 1ms/step - loss: 0.4045 - accuracy: 0.8077
Epoch 86/100
858/858 [==============================] - 1s 1ms/step - loss: 0.4042 - accuracy: 0.8062
Epoch 87/100
858/858 [==============================] - 1s 1ms/step - loss: 0.4048 - accuracy: 0.8073
Epoch 88/100
858/858 [==============================] - 1s 1ms/step - loss: 0.4046 - accuracy: 0.8066
Epoch 89/100
858/858 [==============================] - 1s 1ms/step - loss: 0.4044 - accuracy: 0.8076
Epoch 90/100
849/858 [============================>.] - ETA: 0s - loss: 0.4052 - accuracy: 0.8069
Epoch 90: saving model to checkpoints-Optimization/weights.90.hdf5
858/858 [==============================] - 2s 2ms/step - loss: 0.4041 - accuracy: 0.8076
Epoch 91/100
858/858 [==============================] - 1s 1ms/step - loss: 0.4041 - accuracy: 0.8075
Epoch 92/100
858/858 [==============================] - 1s 1ms/step - loss: 0.4043 - accuracy: 0.8067
Epoch 93/100
858/858 [==============================] - 1s 1ms/step - loss: 0.4042 - accuracy: 0.8057
Epoch 94/100
858/858 [==============================] - 1s 1ms/step - loss: 0.4042 - accuracy: 0.8069
Epoch 95/100
842/858 [============================>.] - ETA: 0s - loss: 0.4030 - accuracy: 0.8082
Epoch 95: saving model to checkpoints-Optimization/weights.95.hdf5
858/858 [==============================] - 1s 1ms/step - loss: 0.4037 - accuracy: 0.8079
Epoch 96/100
858/858 [==============================] - 1s 1ms/step - loss: 0.4039 - accuracy: 0.8076
Epoch 97/100
858/858 [==============================] - 1s 1ms/step - loss: 0.4041 - accuracy: 0.8071
Epoch 98/100
858/858 [==============================] - 1s 1ms/step - loss: 0.4038 - accuracy: 0.8074
Epoch 99/100
858/858 [==============================] - 1s 1ms/step - loss: 0.4037 - accuracy: 0.8068
Epoch 100/100
827/858 [===========================>..] - ETA: 0s - loss: 0.4026 - accuracy: 0.8080
Epoch 100: saving model to checkpoints-Optimization/weights.100.hdf5
858/858 [==============================] - 1s 2ms/step - loss: 0.4037 - accuracy: 0.8073

In [35]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

215/215 - 0s - loss: 0.4619 - accuracy: 0.7835 - 403ms/epoch - 2ms/step
Loss: 0.4619036316871643, Accuracy: 0.783527672290802

In [38]:
# Export our model to HDF5 file
nn.save("models/AlphabetSoupCharity_Optimization.h5")

/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py:3000: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(